spring.application.name=bookstore-ia

# ===== Base de donnees MySQL =====
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=bookstore_user
spring.datasource.password=bookstore_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jackson.serialization.fail-on-empty-beans=false
# ===== Cle secrete JWT =====
JWT_SECRET=bookstore_secret_super_longue_cle_jwt_2024_minimum_32_chars

# ===== API Gemini =====
GEMINI_API_KEY=AIzaSyC3soreVW4ZDvTuZWOm8nc9wRnNcuUl5w0

# ===== Serveur =====
server.port=8080