import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type AppLanguage = 'fr' | 'en';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private readonly storageKey = 'app_language';
  private readonly categoryTranslations: Record<AppLanguage, Record<string, string>> = {
    fr: {
      'Fantasy': 'Fantasy',
      'Science-Fiction': 'Science-fiction',
      'Romans': 'Romans',
      'Classiques': 'Classiques',
      'Classique': 'Classiques',
      'Dystopie': 'Dystopie',
      'Post-Apocalyptique': 'Post-apocalyptique',
      'Fantastique': 'Fantastique',
      'Aventure': 'Aventure',
      'Conte': 'Conte',
      'Roman': 'Roman',
      'Littérature étrangère': 'Littérature étrangère',
      'Roman policier': 'Roman policier',
      'Témoignage': 'Témoignage',
      'BD & Romans graphiques': 'BD & Romans graphiques',
      'Comics': 'Comics',
      'Poésie': 'Poésie',
      'Philosophie': 'Philosophie',
      'Science & Médecine': 'Science & médecine',
      'Histoire': 'Histoire',
      'Essai': 'Essai',
      'Psychologie': 'Psychologie',
      'Développement personnel': 'Développement personnel',
      'Bien-être': 'Bien-être',
      'Science': 'Science'
    },
    en: {
      'Fantasy': 'Fantasy',
      'Science-Fiction': 'Science Fiction',
      'Romans': 'Novels',
      'Classiques': 'Classics',
      'Classique': 'Classics',
      'Dystopie': 'Dystopia',
      'Post-Apocalyptique': 'Post-apocalyptic',
      'Fantastique': 'Fantasy',
      'Aventure': 'Adventure',
      'Conte': 'Fairy tale',
      'Roman': 'Novel',
      'Littérature étrangère': 'World literature',
      'Roman policier': 'Crime fiction',
      'Témoignage': 'Testimony',
      'BD & Romans graphiques': 'Comics & graphic novels',
      'Comics': 'Comics',
      'Poésie': 'Poetry',
      'Philosophie': 'Philosophy',
      'Science & Médecine': 'Science & medicine',
      'Histoire': 'History',
      'Essai': 'Essay',
      'Psychologie': 'Psychology',
      'Développement personnel': 'Self-development',
      'Bien-être': 'Wellness',
      'Science': 'Science'
    }
  };

  private readonly sortTranslations: Record<AppLanguage, Record<string, string>> = {
    fr: {
      featured: 'En vedette',
      'price-asc': 'Prix croissant',
      'price-desc': 'Prix décroissant',
      rating: 'Mieux notés',
      title: 'Titre A-Z',
      newest: 'Nouveautés'
    },
    en: {
      featured: 'Featured',
      'price-asc': 'Price low to high',
      'price-desc': 'Price high to low',
      rating: 'Top rated',
      title: 'Title A-Z',
      newest: 'Newest'
    }
  };
  private readonly translations: Record<AppLanguage, Record<string, string>> = {
    fr: {
      'navbar.searchPlaceholder': 'Rechercher un titre, auteur, catégorie...',
      'navbar.guestGreeting': 'Bonjour,',
      'navbar.login': 'Connexion',
      'navbar.account': 'Mon compte',
      'navbar.profile': 'Mon profil',
      'navbar.wishlist': 'Ma wishlist',
      'navbar.orders': 'Mes commandes',
      'navbar.ordersLink': 'Mes commandes',
      'navbar.logout': 'Se déconnecter',
      'navbar.cart': 'Cart',
      'navbar.toggle': 'EN',
      'profile.wishlist': 'Ma wishlist',
      'profile.savedBooks': 'Livres sauvegardés',
      'profile.infoTab': 'Mes informations',
      'profile.ordersTab': 'Mes commandes',
      'profile.wishlistTab': 'Ma wishlist',
      'profile.accountInfo': 'Informations du compte',
      'profile.username': "Nom d'utilisateur",
      'profile.role': 'Rôle',
      'profile.preferredPayment': 'Paiement préféré',
      'profile.cashOnDelivery': 'Paiement à la livraison (COD)',
      'profile.loading': 'Chargement...',
      'profile.noOrders': 'Aucune commande pour le moment',
      'profile.exploreCatalog': 'Explorer le catalogue',
      'profile.order': 'Commande',
      'profile.logout': 'Déconnexion',
      'profile.ordersCount': 'commande(s)',
      'profile.status.preparation': 'En préparation',
      'profile.status.shipped': 'Expédiée',
      'profile.status.delivered': 'Livrée',
      'orders.title': 'Mes commandes',
      'orders.emptyTitle': 'Aucune commande pour le moment',
      'orders.emptyHint': 'Vos commandes apparaîtront ici après votre premier achat.',
      'orders.exploreCatalog': 'Explorer le catalogue',
      'orders.orderNumber': 'Commande',
      'orders.address': 'Adresse',
      'orders.login': 'Se connecter',
      'orders.loadError': 'Impossible de charger vos commandes. Veuillez vous connecter.',
      'orders.trackOrder': 'Suivre ma commande',
      'orders.status.cancelled': 'Annulée',
      'orders.status.inProgress': 'En cours',
      'orders.commentPrefix': 'Commentaire:',
      'tracking.backToOrders': 'Retour à mes commandes',
      'tracking.order': 'Commande',
      'tracking.placedOn': 'Passée le',
      'tracking.total': 'Total',
      'tracking.cancelledTitle': 'Commande annulée',
      'tracking.cancelledHint': 'Cette commande a été annulée. Le stock a été restitué.',
      'tracking.chronopostNumber': 'Numéro de suivi Chronopost',
      'tracking.followChronopost': 'Suivre sur Chronopost',
      'tracking.orderTracking': 'Suivi de votre commande',
      'tracking.deliveryAddress': 'Adresse de livraison',
      'tracking.payment': 'Paiement',
      'tracking.paymentCod': 'Paiement à la livraison (COD)',
      'tracking.paymentNoOnline': 'Aucun paiement en ligne requis',
      'tracking.items': 'article(s)',
      'tracking.step.EN_PREPARATION.label': 'Commande reçue',
      'tracking.step.EN_PREPARATION.description': 'En cours de préparation',
      'tracking.step.EXPEDIEE.label': 'Expédiée',
      'tracking.step.EXPEDIEE.description': 'Colis en route',
      'tracking.step.LIVREE.label': 'Livrée',
      'tracking.step.LIVREE.description': 'Commande reçue',
      'wishlist.title': 'Ma wishlist',
      'wishlist.count': '{{count}} livre(s) sauvegardé(s)',
      'wishlist.backToProfile': 'Mon profil',
      'wishlist.clearAll': 'Tout supprimer',
      'wishlist.emptyTitle': 'Votre wishlist est vide',
      'wishlist.emptyHint': 'Ajoutez des livres depuis le catalogue en cliquant sur ❤️',
      'wishlist.explore': 'Explorer le catalogue',
      'wishlist.removeTooltip': 'Retirer de la wishlist',
      'wishlist.buy': 'Acheter',
      'cart.title': 'Mon panier',
      'cart.emptyTitle': 'Votre panier est vide',
      'cart.emptyHint': 'Ajoutez des livres depuis la page d\'accueil.',
      'cart.exploreCatalog': 'Explorer le catalogue',
      'cart.remove': 'Supprimer',
      'cart.summary': 'Récapitulatif',
      'cart.subtotal': 'Sous-total ({{count}} articles)',
      'cart.delivery': 'Livraison',
      'cart.freeDelivery': 'GRATUITE',
      'cart.paymentMethod': 'Paiement',
      'cart.cashOnDelivery': 'Cash on delivery',
      'cart.total': 'Total',
      'cart.shippingAddress': 'Adresse de livraison',
      'cart.shippingPlaceholder': 'Numéro, rue, ville, code postal...',
      'cart.addressRequired': 'Adresse de livraison requise.',
      'cart.addressSearching': 'Recherche d\'adresses en France...',
      'cart.comment': 'Commentaire de livraison',
      'cart.commentPlaceholder': 'Ex: Interphone, etage, instructions pour le livreur...',
      'cart.commentPrefix': 'Commentaire',
      'cart.placeOrder': 'Passer la commande',
      'cart.confirmOrder': 'Confirmer la commande',
      'cart.processing': 'Traitement en cours...',
      'cart.cancel': 'Annuler',
      'cart.clear': 'Vider le panier',
      'cart.loginRequired': 'Veuillez vous connecter pour passer une commande.',
      'cart.stockLimitError': 'Stock limite atteint (max {{count}}).',
      'cart.maxQtyReached': 'Quantité maximale atteinte: quantité actuelle = stock disponible ({{count}}).',
      'cart.orderError': 'Erreur lors de la commande. Vérifiez que vous êtes connecté.',
      'bookCard.addToCart': 'Ajouter au panier',
      'bookCard.soldOut': 'Rupture de stock',
      'bookCard.by': 'par',
      'catalog.allCategories': 'Toutes catégories',
      'catalog.onSale': 'En offre',
      'catalog.title': 'Catalogue',
      'catalog.searchResults': 'Résultats pour "{{query}}"',
      'catalog.booksFound': '{{count}} livre(s) trouvé(s)',
      'catalog.noBooks': 'Aucun livre trouvé',
      'catalog.noBooksHint': 'Essayez un autre mot-clé ou une autre catégorie',
      'catalog.reset': 'Réinitialiser',
      'sort.featured': 'En vedette',
      'sort.priceAsc': 'Prix croissant',
      'sort.priceDesc': 'Prix décroissant',
      'sort.rating': 'Mieux notés',
      'sort.title': 'Titre A-Z',
      'home.badge': 'Nouveautés disponibles',
      'home.title.line1': 'Découvrez votre',
      'home.title.line2': 'prochain livre',
      'home.heroText1': 'Des milliers de livres livrés à domicile.',
      'home.heroText2': 'Paiement à la livraison disponible.',
      'home.explore': 'Explorer le catalogue',
      'home.browse': 'Parcourir',
      'home.clearFilters': 'Effacer',
      'home.sortBy': 'Trier par :',
      'home.pricePrefix': 'Prix :',
      'home.booksFound': '{{count}} livre(s) trouvé(s)',
      'home.booksAvailable': 'Livres disponibles',
      'home.noteMoyenne': 'Note moyenne',
      'home.delivery': 'Livraison express',
      'sidebar.categories': 'Catégories',
      'sidebar.price': 'Prix',
      'sidebar.loading': 'Chargement...',
      'sidebar.lessThan10': 'Moins de 10 €',
      'sidebar.between10and25': '10 € à 25 €',
      'sidebar.between25and50': '25 € à 50 €',
      'sidebar.between50and100': '50 € à 100 €',
      'bookDetails.notFound': 'Livre introuvable',
      'bookDetails.backToCatalog': '← Retour au catalogue',
      'bookDetails.breadcrumb.home': 'Accueil',
      'bookDetails.breadcrumb.catalog': 'Catalogue',
      'bookDetails.loading': 'Chargement du livre...',
      'bookDetails.by': 'par',
      'bookDetails.unknownAuthor': 'Auteur inconnu',
      'bookDetails.unknownDescription': 'Aucune description disponible.',
      'bookDetails.addToCart': 'Ajouter au panier',
      'bookDetails.addToWishlist': 'Ajouter aux favoris',
      'bookDetails.removeFromWishlist': 'Retiré des favoris',
      'bookDetails.aiSummaryTitle': 'Résumé par Gemini AI',
      'bookDetails.generate': 'Générer',
      'bookDetails.loginToSummary': 'Connectez-vous',
      'bookDetails.loginToSummaryMessage': 'pour obtenir un résumé IA.',
      'bookDetails.generatingSummary': 'Gemini génère un résumé...',
      'bookDetails.clickGenerate': 'Cliquez sur "Générer" pour obtenir un résumé intelligent de ce livre.',
      'bookDetails.reviewsTitle': 'Avis clients',
      'bookDetails.giveReview': 'Donner mon avis',
      'bookDetails.reviewPlaceholder': 'Partagez votre expérience...',
      'bookDetails.publishReview': 'Publier l\'avis',
      'bookDetails.loginToReview': 'Connectez-vous',
      'bookDetails.loginToReviewMessage': 'pour laisser un avis.',
      'bookDetails.reviewsLabel': 'avis',
      'bookDetails.noReviews': 'Aucun avis pour l\'instant. Soyez le premier !',
      'bookDetails.anonymous': 'Anonyme',
      'bookDetails.reviewPublished': 'Avis publié avec succès !',
      'bookDetails.reviewError': 'Erreur lors de la publication.',
      'bookDetails.addedToWishlist': 'Ajouté aux favoris !',
      'bookDetails.summaryError': 'Impossible de générer le résumé.',
      'home.reco.personalized': 'Recommandé pour vous',
      'home.reco.purchaseBased': 'Recommandé selon vos achats',
      'home.reco.trending': 'Tendances du moment',
      'home.reco.subtitle.personalized': 'Sélectionné par Gemini AI selon votre historique d\'achats',
      'home.reco.subtitle.trending': 'Les livres les mieux notés de la semaine',
      'home.reco.badge.personalized': '✦ IA Personnalisé',
      'home.reco.badge.trending': '✧ Top Livres',
      'navbar.nav.home': 'Accueil',
      'navbar.nav.bestSellers': 'Meilleures ventes',
      'navbar.nav.newArrivals': 'Nouveautés',
      'home.reco.loading': 'Chargement des livres...',
      'home.reco.noBooks': 'Aucun livre dans cette catégorie',
      'home.reco.viewAll': 'Voir tous les livres',
      'home.reco.top': 'Top Livres'
    },
    en: {
      'navbar.searchPlaceholder': 'Search by title, author, category...',
      'navbar.guestGreeting': 'Hello,',
      'navbar.login': 'Login',
      'navbar.account': 'My account',
      'navbar.profile': 'My profile',
      'navbar.wishlist': 'My wishlist',
      'navbar.orders': 'My orders',
      'navbar.ordersLink': 'My orders',
      'navbar.logout': 'Logout',
      'navbar.cart': 'Cart',
      'navbar.toggle': 'FR',
      'profile.wishlist': 'My wishlist',
      'profile.savedBooks': 'Saved books',
      'profile.infoTab': 'My information',
      'profile.ordersTab': 'My orders',
      'profile.wishlistTab': 'My wishlist',
      'profile.accountInfo': 'Account information',
      'profile.username': 'Username',
      'profile.role': 'Role',
      'profile.preferredPayment': 'Preferred payment',
      'profile.cashOnDelivery': 'Cash on delivery (COD)',
      'profile.loading': 'Loading...',
      'profile.noOrders': 'No orders yet',
      'profile.exploreCatalog': 'Browse catalog',
      'profile.order': 'Order',
      'profile.logout': 'Logout',
      'profile.ordersCount': 'order(s)',
      'profile.status.preparation': 'Preparing',
      'profile.status.shipped': 'Shipped',
      'profile.status.delivered': 'Delivered',
      'orders.title': 'My orders',
      'orders.emptyTitle': 'No orders yet',
      'orders.emptyHint': 'Your orders will appear here after your first purchase.',
      'orders.exploreCatalog': 'Browse catalog',
      'orders.orderNumber': 'Order',
      'orders.address': 'Address',
      'orders.login': 'Log in',
      'orders.loadError': 'Unable to load your orders. Please log in.',
      'orders.trackOrder': 'Track my order',
      'orders.status.cancelled': 'Cancelled',
      'orders.status.inProgress': 'In progress',
      'orders.commentPrefix': 'Comment:',
      'tracking.backToOrders': 'Back to my orders',
      'tracking.order': 'Order',
      'tracking.placedOn': 'Placed on',
      'tracking.total': 'Total',
      'tracking.cancelledTitle': 'Order cancelled',
      'tracking.cancelledHint': 'This order has been cancelled. Stock has been restored.',
      'tracking.chronopostNumber': 'Chronopost tracking number',
      'tracking.followChronopost': 'Track on Chronopost',
      'tracking.orderTracking': 'Track your order',
      'tracking.deliveryAddress': 'Shipping address',
      'tracking.payment': 'Payment',
      'tracking.paymentCod': 'Cash on delivery (COD)',
      'tracking.paymentNoOnline': 'No online payment required',
      'tracking.items': 'item(s)',
      'tracking.step.EN_PREPARATION.label': 'Order received',
      'tracking.step.EN_PREPARATION.description': 'Being prepared',
      'tracking.step.EXPEDIEE.label': 'Shipped',
      'tracking.step.EXPEDIEE.description': 'Package in transit',
      'tracking.step.LIVREE.label': 'Delivered',
      'tracking.step.LIVREE.description': 'Order received',
      'wishlist.title': 'My wishlist',
      'wishlist.count': '{{count}} saved book(s)',
      'wishlist.backToProfile': 'My profile',
      'wishlist.clearAll': 'Clear all',
      'wishlist.emptyTitle': 'Your wishlist is empty',
      'wishlist.emptyHint': 'Add books from the catalog by clicking ❤️',
      'wishlist.explore': 'Browse catalog',
      'wishlist.removeTooltip': 'Remove from wishlist',
      'wishlist.buy': 'Buy',
      'cart.title': 'My cart',
      'cart.emptyTitle': 'Your cart is empty',
      'cart.emptyHint': 'Add books from the home page.',
      'cart.exploreCatalog': 'Browse catalog',
      'cart.remove': 'Remove',
      'cart.summary': 'Summary',
      'cart.subtotal': 'Subtotal ({{count}} items)',
      'cart.delivery': 'Delivery',
      'cart.freeDelivery': 'FREE',
      'cart.paymentMethod': 'Payment',
      'cart.cashOnDelivery': 'Cash on delivery',
      'cart.total': 'Total',
      'cart.shippingAddress': 'Shipping address',
      'cart.shippingPlaceholder': 'Number, street, city, postal code...',
      'cart.addressRequired': 'Shipping address is required.',
      'cart.addressSearching': 'Searching addresses in France...',
      'cart.comment': 'Delivery comment',
      'cart.commentPlaceholder': 'Ex: Door code, floor, delivery instructions...',
      'cart.commentPrefix': 'Comment',
      'cart.placeOrder': 'Place order',
      'cart.confirmOrder': 'Confirm order',
      'cart.processing': 'Processing...',
      'cart.cancel': 'Cancel',
      'cart.clear': 'Clear cart',
      'cart.loginRequired': 'Please log in to place an order.',
      'cart.stockLimitError': 'Stock limit reached (max {{count}}).',
      'cart.maxQtyReached': 'Maximum quantity reached: current quantity = available stock ({{count}}).',
      'cart.orderError': 'Order failed. Please verify that you are logged in.',
      'bookCard.addToCart': 'Add to cart',
      'bookCard.soldOut': 'Sold out',
      'bookCard.by': 'by',
      'catalog.allCategories': 'All categories',
      'catalog.onSale': 'Offers',
      'catalog.title': 'Catalog',
      'catalog.searchResults': 'Results for "{{query}}"',
      'catalog.booksFound': '{{count}} books found',
      'catalog.noBooks': 'No books found',
      'catalog.noBooksHint': 'Try another keyword or another category',
      'catalog.reset': 'Reset',
      'sort.featured': 'Featured',
      'sort.priceAsc': 'Price low to high',
      'sort.priceDesc': 'Price high to low',
      'sort.rating': 'Top rated',
      'sort.title': 'Title A-Z',
      'home.badge': 'New arrivals available',
      'home.title.line1': 'Discover your',
      'home.title.line2': 'next book',
      'home.heroText1': 'Thousands of books delivered to your door.',
      'home.heroText2': 'Cash on delivery available.',
      'home.explore': 'Browse catalog',
      'home.browse': 'Browse',
      'home.clearFilters': 'Clear',
      'home.sortBy': 'Sort by:',
      'home.pricePrefix': 'Price:',
      'home.booksFound': '{{count}} books found',
      'home.booksAvailable': 'Books available',
      'home.noteMoyenne': 'Average rating',
      'home.delivery': 'Express delivery',
      'sidebar.categories': 'Categories',
      'sidebar.price': 'Price',
      'sidebar.loading': 'Loading...',
      'sidebar.lessThan10': 'Less than €10',
      'sidebar.between10and25': '€10 to €25',
      'sidebar.between25and50': '€25 to €50',
      'sidebar.between50and100': '€50 to €100',
      'bookDetails.notFound': 'Book not found',
      'bookDetails.backToCatalog': '← Back to catalog',
      'bookDetails.breadcrumb.home': 'Home',
      'bookDetails.breadcrumb.catalog': 'Catalog',
      'bookDetails.loading': 'Loading book...',
      'bookDetails.by': 'by',
      'bookDetails.unknownAuthor': 'Unknown author',
      'bookDetails.unknownDescription': 'No description available.',
      'bookDetails.addToCart': 'Add to cart',
      'bookDetails.addToWishlist': 'Add to wishlist',
      'bookDetails.removeFromWishlist': 'Removed from wishlist',
      'bookDetails.aiSummaryTitle': 'Summary by Gemini AI',
      'bookDetails.generate': 'Generate',
      'bookDetails.loginToSummary': 'Log in',
      'bookDetails.loginToSummaryMessage': 'to get an AI summary.',
      'bookDetails.generatingSummary': 'Gemini is generating a summary...',
      'bookDetails.clickGenerate': 'Click "Generate" to get a smart summary of this book.',
      'bookDetails.reviewsTitle': 'Customer reviews',
      'bookDetails.giveReview': 'Write a review',
      'bookDetails.reviewPlaceholder': 'Share your experience...',
      'bookDetails.publishReview': 'Publish review',
      'bookDetails.loginToReview': 'Log in',
      'bookDetails.loginToReviewMessage': 'to leave a review.',
      'bookDetails.reviewsLabel': 'reviews',
      'bookDetails.noReviews': 'No reviews yet. Be the first!',
      'bookDetails.anonymous': 'Anonymous',
      'bookDetails.reviewPublished': 'Review published successfully!',
      'bookDetails.reviewError': 'Error while publishing the review.',
      'bookDetails.addedToWishlist': 'Added to wishlist!',
      'bookDetails.summaryError': 'Unable to generate the summary.',
      'home.reco.personalized': 'Recommended for you',
      'home.reco.purchaseBased': 'Recommended from your purchases',
      'home.reco.trending': 'Trending now',
      'home.reco.subtitle.personalized': 'Selected by Gemini AI based on your purchase history',
      'home.reco.subtitle.trending': 'The highest-rated books of the week',
      'home.reco.badge.personalized': '✦ AI Personalized',
      'home.reco.badge.trending': '✧ Top Books',
      'navbar.nav.home': 'Home',
      'navbar.nav.bestSellers': 'Best sellers',
      'navbar.nav.newArrivals': 'New arrivals',
      'home.reco.loading': 'Loading books...',
      'home.reco.noBooks': 'No books in this category',
      'home.reco.viewAll': 'See all books',
      'home.reco.top': 'Top Books'
    }
  };

  private readonly language$ = new BehaviorSubject<AppLanguage>(this.loadLanguage());

  get currentLanguage(): AppLanguage {
    return this.language$.value;
  }

  currentLanguageChanges() {
    return this.language$.asObservable();
  }

  setLanguage(language: AppLanguage): void {
    this.language$.next(language);
    localStorage.setItem(this.storageKey, language);
  }

  toggleLanguage(): void {
    this.setLanguage(this.currentLanguage === 'fr' ? 'en' : 'fr');
  }

  t(key: string): string {
    return this.translations[this.currentLanguage][key] ?? key;
  }

  categoryLabel(category: string): string {
    if (category === '__offers__') {
      return this.currentLanguage === 'fr' ? 'En offre' : 'On sale';
    }
    return this.categoryTranslations[this.currentLanguage][category] ?? category;
  }

  sortLabel(sort: string): string {
    return this.sortTranslations[this.currentLanguage][sort] ?? sort;
  }

  private loadLanguage(): AppLanguage {
    const stored = localStorage.getItem(this.storageKey);
    return stored === 'en' ? 'en' : 'fr';
  }
}